Repository bankidz/bankidz-server, pull requests merged in 2022-08, with the labels that each got.

#95 refactor: v0.1.1 로직 유지보수 쉽게 리팩토링
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Refactor, For: Deploy

#98 refactor: 자녀의 돈길 리스트 API 리팩토링
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#99 refactor: 가족 정보, 자녀 리스트 조회 API 수정
  src/main/java/com/ceos/bankids/dto/KidListDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#100 [v0.1.2] 리팩토링 버전 배포
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/dto/KidListDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#103 fix: 자녀의 주차 정보 API pathVariable로 리팩토링 #102
  src/main/java/com/ceos/bankids/config/S3Config.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/dto/ProgressDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
Labels: For: API, Type: Errors/Bugs, Type: Refactor, Type: Test, For: Deploy

#105 fix: 완주한 돈길은 accept에서 가져오기 #104
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
Labels: For: API, Type: Errors/Bugs, Type: Refactor, Type: Test

#107 feat: S3 추가
  build.gradle
  src/main/java/com/ceos/bankids/config/S3Config.java
  src/main/java/com/ceos/bankids/controller/S3Controller.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/PreSignedDTO.java
  src/main/java/com/ceos/bankids/service/S3Service.java
  src/main/java/com/ceos/bankids/service/S3ServiceImpl.java
  src/main/resources/application.properties
Labels: For: Utils, Type: Feature

#109 feature: 부모 마이페이지 기획 및 뷰 수정에 따라 코드 작성
  src/main/java/com/ceos/bankids/dto/KidListDTO.java
  src/main/java/com/ceos/bankids/dto/ParentDTO.java
Labels: For: API, Type: Feature, Type: Refactor

#110 fix: 시간 로직 전면 수정
  build.gradle
  src/main/java/com/ceos/bankids/config/S3Config.java
  src/main/java/com/ceos/bankids/controller/S3Controller.java
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor, Type: Test

#112 refactor: parent의 totalChallenge / savings 날리기
  src/main/java/com/ceos/bankids/domain/Parent.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Utils, Type: Refactor

#113 [v0.1.3] QA용으로 수정한 버전 배포
  build.gradle
  src/main/java/com/ceos/bankids/config/S3Config.java
  src/main/java/com/ceos/bankids/controller/S3Controller.java
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Parent.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/KidListDTO.java
  src/main/java/com/ceos/bankids/dto/ParentDTO.java
  src/main/java/com/ceos/bankids/dto/PreSignedDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/java/com/ceos/bankids/service/S3Service.java
  src/main/java/com/ceos/bankids/service/S3ServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Deploy

#114 fix: v0.1.3 이자율 실패 로직 이상 => 초과로 수정
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: Deploy

#118 fix: v0.1.3버전에서 자녀의 돈길 리스트 가져오기 API 수정
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: Deploy

#119 fix: v0.1.3버전에서 자녀의 돈길 리스트 한번 더 수정
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: Deploy

#123 refactor: v0.1.4버전에서 자녀의 주차 정보 API response 수정
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/dto/KidWeekDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
Labels: For: API, Type: Refactor

#124 feat: ENUM 추가중 #121
  src/main/java/com/ceos/bankids/ENUM/ChallengeStatus.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
Labels: For: API, For: Utils, Type: Refactor, Type: Test

#125 refactor: status / isAchieved enum으로 리팩토링
  src/main/java/com/ceos/bankids/Enum/ChallengeStatus.java
  src/main/java/com/ceos/bankids/Enum/EnumMapperType.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Kid.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: API, For: Utils, Type: Refactor, Type: Test

#126 v0.1.5 Enum으로 리팩토링 및 전면 수정
  src/main/java/com/ceos/bankids/Enum/ChallengeStatus.java
  src/main/java/com/ceos/bankids/Enum/EnumMapperType.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Kid.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: Type: Refactor, Type: Test, For: Deploy

#127 refactor: 자녀 / 부모 마이페이지에 들어가는 내용들 정리 및 리팩
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
Labels: For: API, Type: Refactor

#129 feat: 돈길 완주 시 유저 레벨업 추가
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor

#131 feat: firebase 설정과 초기화 까지
  .github/workflows/dev-deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationService.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/resources/application.properties
Labels: For: Utils, Type: Feature

#132 feat: 돈길 리스트 API 리팩 및 파이어베이스 설정 파일 github action 추가
  .github/workflows/prod-deploy.yml
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor, Type: Test

#133 feat: 가족 초대/참여하기
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/request/FamilyRequest.java
  src/main/java/com/ceos/bankids/repository/FamilyRepository.java
  src/main/java/com/ceos/bankids/repository/FamilyUserRepository.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/JwtTokenService.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#135 feat: 에러 핸들링
  src/main/java/com/ceos/bankids/Enum/EnumMapperType.java
  src/main/java/com/ceos/bankids/config/CommonResponse.java
  src/main/java/com/ceos/bankids/constant/ChallengeStatus.java
  src/main/java/com/ceos/bankids/constant/EnumMapperType.java
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: Utils, Type: Feature

#136 refactor: challenge / progress / S3 서비스 레이어 에러 처리 리팩토링
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/java/com/ceos/bankids/service/S3ServiceImpl.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor

#140 feat: challengeStatus 변경 알림 (자녀측)
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/ChallengeNotification.java
  src/main/java/com/ceos/bankids/dto/FcmMessageDTO.java
  src/main/java/com/ceos/bankids/repository/ChallengeNotificationRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationService.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
Labels: For: Utils, Type: Feature

#142 fix: s3 presigned url 수정
  src/main/java/com/ceos/bankids/dto/PreSignedDTO.java
  src/main/java/com/ceos/bankids/service/S3ServiceImpl.java
Labels: For: API, Status: URGENT, Type: Errors/Bugs

#143 feat: 가족 나가기 API 가족 부분 구현
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#144 feat: 가족 나가기 API 돈길 관련 부분 처리
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/domain/Parent.java
  src/main/java/com/ceos/bankids/repository/CommentRepository.java
  src/main/java/com/ceos/bankids/repository/ParentRepository.java
  src/main/java/com/ceos/bankids/repository/ProgressRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Feature

#146 v0.2.0 버전 배포
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  .gitignore
  build.gradle
  src/main/java/com/ceos/bankids/Enum/EnumMapperType.java
  src/main/java/com/ceos/bankids/config/CommonResponse.java
  src/main/java/com/ceos/bankids/constant/ChallengeStatus.java
  src/main/java/com/ceos/bankids/constant/EnumMapperType.java
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/controller/request/FamilyRequest.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/ChallengeNotification.java
  src/main/java/com/ceos/bankids/domain/Parent.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/FcmMessageDTO.java
  src/main/java/com/ceos/bankids/dto/PreSignedDTO.java
  src/main/java/com/ceos/bankids/repository/ChallengeNotificationRepository.java
  src/main/java/com/ceos/bankids/repository/CommentRepository.java
  src/main/java/com/ceos/bankids/repository/FamilyRepository.java
  src/main/java/com/ceos/bankids/repository/FamilyUserRepository.java
  src/main/java/com/ceos/bankids/repository/ParentRepository.java
  src/main/java/com/ceos/bankids/repository/ProgressRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/JwtTokenService.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationService.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/java/com/ceos/bankids/service/S3ServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: Deploy

#148 refactor: fcm 서버에 요청 하는 방식 okHttp 패키지 사용으로 변경 #137
  build.gradle
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationService.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor

#149 feat: 가족 중 부모가 나갔을 때, 돈길 관련 row 및 컬럼 정보들 초기화 #139
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Feature

#152 feat: 돈길 상태 변경 푸시 알림 테스트 성공
  build.gradle
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: API, For: Utils, Type: Feature, Type: Refactor

#154 feat: 자녀 레벨업 관련 푸시알림 작성
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: API, For: Utils, Type: Feature

#156 feat: 부모한테 전송되는 푸시알림들 로직 작성
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
Labels: For: API, For: Utils, Type: Feature

#158 refactor: 푸시 알림 title/ body 워딩 수정
  src/main/java/com/ceos/bankids/controller/NotificationController.java
Labels: For: Utils, Type: Refactor

#160 feat: 돈길 실패 시 부모 알림 로직 작성 #157
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, For: Utils, Type: Feature

#151 feat: 애플 로그인
  build.gradle
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/request/AppleRequest.java
  src/main/java/com/ceos/bankids/controller/request/AppleUserRequest.java
  src/main/java/com/ceos/bankids/controller/request/AppleUsernameRequest.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleHeaderDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleJwtDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleKeyDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleKeyListDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleTokenDTO.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/resources/application.properties
Labels: For: API, Type: Feature

#162 feat: 로그아웃
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#164 feat: 모든 유저 공지 푸시 알림 로직 작성
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/request/AllSendNotificationRequest.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/repository/ChallengeNotificationRepository.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
Labels: For: API, Type: Feature

#166 refactor: 자녀의 돈길 리스트 API DTO 수정 #165
  src/main/java/com/ceos/bankids/dto/KidChallengeListDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
Labels: For: API, Type: Refactor

#167 feat: 미가입 회원일 시 유저 정보와 함께 디비 등록 #163
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/request/AppleRequest.java
  src/main/java/com/ceos/bankids/controller/request/AppleUserRequest.java
  src/main/java/com/ceos/bankids/controller/request/AppleUsernameRequest.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
Labels: For: API, Type: Feature

#168 v0.3.0 버전 배포
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  build.gradle
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/AllSendNotificationRequest.java
  src/main/java/com/ceos/bankids/controller/request/AppleRequest.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/dto/KidChallengeListDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleHeaderDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleJwtDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleKeyDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleKeyListDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleTokenDTO.java
  src/main/java/com/ceos/bankids/repository/ChallengeNotificationRepository.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/NotificationService.java
  src/main/java/com/ceos/bankids/service/NotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Deploy

#171 refactor: 돈길 걸었을 때 바뀌는 돈길 상태에 대하여 DTO 수정 #170
  src/main/java/com/ceos/bankids/dto/ProgressDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
Labels: For: API, Type: Refactor
