Repository bankidz/bankidz-server, pull requests merged in 2022-09, with the labels that each got.

#173 feat: 유저 탈퇴
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/WithdrawalRequest.java
  src/main/java/com/ceos/bankids/domain/KidBackup.java
  src/main/java/com/ceos/bankids/domain/ParentBackup.java
  src/main/java/com/ceos/bankids/dto/FamilyUserDTO.java
  src/main/java/com/ceos/bankids/dto/KidBackupDTO.java
  src/main/java/com/ceos/bankids/dto/KidDTO.java
  src/main/java/com/ceos/bankids/dto/KidListDTO.java
  src/main/java/com/ceos/bankids/dto/MyPageDTO.java
  src/main/java/com/ceos/bankids/dto/ParentBackupDTO.java
  src/main/java/com/ceos/bankids/dto/ParentDTO.java
  src/main/java/com/ceos/bankids/dto/UserDTO.java
  src/main/java/com/ceos/bankids/repository/KidBackupRepository.java
  src/main/java/com/ceos/bankids/repository/ParentBackupRepository.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidBackupService.java
  src/main/java/com/ceos/bankids/service/KidBackupServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentBackupService.java
  src/main/java/com/ceos/bankids/service/ParentBackupServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
  src/main/java/com/ceos/bankids/service/SlackService.java
  src/main/java/com/ceos/bankids/service/SlackServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#175 feat: 애플 로그인 및 연동 해제, 엑스포 토큰
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/KakaoController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/ExpoRequest.java
  src/main/java/com/ceos/bankids/dto/LoginDTO.java
  src/main/java/com/ceos/bankids/dto/oauth/AppleSubjectDTO.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoService.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/KakaoControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#176 feat: 완주한 돈길만 가져오기 API 작성
  src/main/java/com/ceos/bankids/constant/ChallengeStatus.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/dto/KidChallengeListDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Feature, Type: Refactor

#179 feat: 새로운 가족 참여시 푸시 알림
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/dto/FamilyDTO.java
  src/main/java/com/ceos/bankids/dto/FamilyUserDTO.java
  src/main/java/com/ceos/bankids/repository/FamilyUserRepository.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, For: Utils, Type: Feature, Type: Test

#180 feat: 완주한 돈길만 가져오기 API에 쿼리파라미터로 이자 지급 여부 판단 기능 추가 #177
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/dto/KidChallengeListDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Feature

#182 feat: 전체 알림 기능 추가 및 유저 토큰 받아오기 로직 추가 #181
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Utils, Type: Feature, Type: Refactor

#184 refactor: 에러 및 자잘한 코드 변경
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor

#185 완주한 돈길 모아보기 및 자녀의 완주한 돈길 모아보기 및 이자지급 API 작성
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/dto/AchievedChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/AchievedChallengeListDTO.java
  src/main/java/com/ceos/bankids/dto/KidAchievedChallengeListDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Feature, Type: Refactor

#190 v0.4.1 버전 배포
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/NoticeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/request/NoticeRequest.java
  src/main/java/com/ceos/bankids/domain/Notice.java
  src/main/java/com/ceos/bankids/dto/AllSendNotificationDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeListDTO.java
  src/main/java/com/ceos/bankids/repository/NoticeRepository.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/NoticeService.java
  src/main/java/com/ceos/bankids/service/NoticeServiceImpl.java
Labels: For: API, For: Utils, Type: Feature

#191 feat: 알림 관련 API 2개 추가 #189
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: API, Type: Feature

#192 v0.5.0
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#194 chore: 웹훅 주소 main 추가
  .github/workflows/prod-deploy.yml
Labels: For: Deploy

#195 refactor: 어드민 계정 유저 아이디 변경으로 인한 리팩
  src/main/java/com/ceos/bankids/controller/NoticeController.java
Labels: For: Deploy

#196 v0.5.1
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
Labels: For: Utils, Type: Docs/Chore

#198 feat: 유저 푸시알림 동의
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/dto/OptInDTO.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#199 refactor: 알림 리스트 페이지네이션으로 리팩
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationListDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: API, Type: Feature, Type: Refactor

#200 v0.6.0 버전 배포
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationListDTO.java
  src/main/java/com/ceos/bankids/dto/OptInDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/ProgressControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Deploy

#201 v0.6.1
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature

#202 feat: 알림 리스트 가져오기 수정
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/dto/NotificationListDTO.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#204 fix: QA 1차 대응
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
Labels: For: API, For: Utils, Type: Refactor

#205 v0.7.0 버전 배포
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
Labels: For: Deploy

#208 refactor: 알림에 카테고리 Enum으로 추가 및 알림 전부 읽었는지 확인하는 api 추가
  src/main/java/com/ceos/bankids/constant/NotificationCategory.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationIsReadDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: API, Type: Feature, Type: Refactor

#209 v0.7.0
  src/main/java/com/ceos/bankids/constant/NotificationCategory.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationIsReadDTO.java
  src/main/java/com/ceos/bankids/repository/NotificationRepository.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Deploy

#210 fix: 알림리스트 페이지네이션 오류 수정
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#213 feat: 알림 동의 여부 조회 API
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#215 feat: notification 테이블 및 dto에 linkUrl 추가
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: API, For: Utils, Type: Feature

#216 fix: 유저 관련 문제
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
Labels: For: API, Type: Docs/Chore, Type: Errors/Bugs, Type: Refactor

#217 v0.7.1
  .github/workflows/dev-deploy.yml
  src/main/java/com/ceos/bankids/config/security/WebSecurityConfig.java
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/domain/Notification.java
  src/main/java/com/ceos/bankids/domain/User.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: Deploy

#218 fix: expoPushToken이 expoenetPushToken으로 시작하지 않는다면 빼고 알림 전송
  src/main/java/com/ceos/bankids/controller/NoticeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#219 fix: DI 순환참조 해결
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#220 refactor: notice / notification으로 저장될 때 url 수정
  src/main/java/com/ceos/bankids/controller/NoticeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
Labels: For: Deploy

#222 feat: refresh API aT 사용하는 것으로 변경
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/TokenRequest.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Feature, Type: Test

#224 refactor: UserController API 리팩토링
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/KakaoController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/service/JwtTokenService.java
  src/main/java/com/ceos/bankids/service/JwtTokenServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/KakaoControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
  src/test/java/com/ceos/bankids/unit/service/JwtTokenServiceTest.java
Labels: For: API, Type: Refactor, Type: Test

#226 [REFACTOR] refresh API 수정
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/TokenRequest.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#228 [REFACTOR] FamilyController API 리팩토링
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/KakaoController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/repository/FamilyUserRepository.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyUserService.java
  src/main/java/com/ceos/bankids/service/FamilyUserServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/KakaoControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#231 refactor: 돈길 관련 API 및 로직들 리팩토링
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/controller/ProgressController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/dto/ChallengeCompleteDeleteByKidMapperDTO.java
  src/main/java/com/ceos/bankids/dto/ChallengeCompleteDeleteByParentMapperDTO.java
  src/main/java/com/ceos/bankids/repository/ChallengeUserRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ChallengeUserService.java
  src/main/java/com/ceos/bankids/service/ChallengeUserServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
  src/main/java/com/ceos/bankids/service/ProgressServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Errors/Bugs, Type: Feature, Type: Refactor

#233 refactor: 파사드 패턴을 이용하여 돈길 관련 Mapper 레이어로 리팩토링
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/service/ChallengeUserService.java
  src/main/java/com/ceos/bankids/service/ChallengeUserServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
Labels: For: API, Type: Feature, Type: Refactor

#235 refactor: 알림 서비스 구조 리팩토링
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/NotificationController.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/FamilyController.java
  src/main/java/com/ceos/bankids/mapper/NoticeController.java
  src/main/java/com/ceos/bankids/mapper/NotificationController.java
  src/main/java/com/ceos/bankids/mapper/NotificationMapper.java
  src/main/java/com/ceos/bankids/mapper/UserController.java
  src/main/java/com/ceos/bankids/service/ChallengeUserService.java
  src/main/java/com/ceos/bankids/service/ChallengeUserServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationService.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor

#237 refactor: 유저 API Mapper 구조 리팩토링
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/controller/HealthCheckController.java
  src/main/java/com/ceos/bankids/controller/KakaoController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/controller/request/AppleRequest.java
  src/main/java/com/ceos/bankids/controller/request/ChallengeRequest.java
  src/main/java/com/ceos/bankids/controller/request/ExpoRequest.java
  src/main/java/com/ceos/bankids/controller/request/FamilyRequest.java
  src/main/java/com/ceos/bankids/controller/request/KakaoRequest.java
  src/main/java/com/ceos/bankids/controller/request/KidChallengeRequest.java
  src/main/java/com/ceos/bankids/controller/request/NoticeRequest.java
  src/main/java/com/ceos/bankids/controller/request/UserTypeRequest.java
  src/main/java/com/ceos/bankids/controller/request/WithdrawalRequest.java
  src/main/java/com/ceos/bankids/dto/ChallengePostDTO.java
  src/main/java/com/ceos/bankids/mapper/AppleMapper.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/FamilyController.java
  src/main/java/com/ceos/bankids/mapper/KakaoController.java
  src/main/java/com/ceos/bankids/mapper/KakaoMapper.java
  src/main/java/com/ceos/bankids/mapper/NoticeController.java
  src/main/java/com/ceos/bankids/mapper/UserController.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/service/AppleService.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/KakaoService.java
  src/main/java/com/ceos/bankids/service/KakaoServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/AppleControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/HealthCheckControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/KakaoControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#240 refactor: 가족 API Mapper 구조 리팩토링
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/controller/FamilyController.java
  src/main/java/com/ceos/bankids/controller/KakaoController.java
  src/main/java/com/ceos/bankids/controller/UserController.java
  src/main/java/com/ceos/bankids/mapper/AppleMapper.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/FamilyController.java
  src/main/java/com/ceos/bankids/mapper/FamilyMapper.java
  src/main/java/com/ceos/bankids/mapper/KakaoMapper.java
  src/main/java/com/ceos/bankids/mapper/NoticeController.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/service/FamilyService.java
  src/main/java/com/ceos/bankids/service/FamilyServiceImpl.java
  src/main/java/com/ceos/bankids/service/FamilyUserService.java
  src/main/java/com/ceos/bankids/service/FamilyUserServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
  src/main/java/com/ceos/bankids/service/UserService.java
  src/main/java/com/ceos/bankids/service/UserServiceImpl.java
Labels: For: API, Type: Refactor

#242 refactor: 유저, 가족 API 테스트 코드 리팩토링
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor, Type: Test

#244 fix: API 컨트롤러 파일 경로 수정 및 쿼리 스트링 문법 수정
  src/main/java/com/ceos/bankids/controller/NoticeController.java
  src/main/java/com/ceos/bankids/controller/S3Controller.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest2.java
Labels: For: API, Type: Errors/Bugs

#246 refactor: 가족 조회하기 API 리스폰스 수정
  src/main/java/com/ceos/bankids/mapper/FamilyMapper.java
  src/test/java/com/ceos/bankids/unit/controller/ChallengeControllerTest2.java
  src/test/java/com/ceos/bankids/unit/controller/FamilyControllerTest.java
Labels: For: API, Type: Refactor, Type: Test
