Repository bankidz/bankidz-server, pull requests merged in 2022-11, with the labels that each got.

#259 refactor: 생년월일 미입력 허용
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor

#260 v1.1.3 버전 배포
  README.md
  src/main/java/com/ceos/bankids/BankidsApplication.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/ChallengeUser.java
  src/main/java/com/ceos/bankids/domain/Comment.java
  src/main/java/com/ceos/bankids/domain/Progress.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor

#262 fix: 돈길 softdelete 전략 유저 탈퇴 문제로 잠시 주석처리
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/ChallengeUser.java
  src/main/java/com/ceos/bankids/domain/Comment.java
  src/main/java/com/ceos/bankids/domain/Progress.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Errors/Bugs

#263 refactor: 미가입 생년월일 빈 문자열 대신 99999999로 변경
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Refactor

#264 fix: deletedAt관련 Repository 메서드 수정 #261
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
Labels: For: API, Type: Errors/Bugs

#265 v1.1.4 버전 배포
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/domain/Challenge.java
  src/main/java/com/ceos/bankids/domain/ChallengeUser.java
  src/main/java/com/ceos/bankids/domain/Comment.java
  src/main/java/com/ceos/bankids/domain/Progress.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/repository/ChallengeRepository.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/test/java/com/ceos/bankids/unit/controller/UserControllerTest.java
Labels: For: API, Type: Errors/Bugs, Type: Refactor

#266 fix: 테스트위해 일요일 validation 해제
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
Labels: For: Deploy

#267 fix: Expotoken 값 null 이여도 처리 로직 변경
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#269 fix: timeStamp NAN 대응 #268
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeListDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/OptInDTO.java
  src/main/java/com/ceos/bankids/dto/ProgressDTO.java
Labels: For: API, Status: URGENT, Type: Errors/Bugs

#271 feat: 다중기기 접속 방지
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
Labels: For: API, Type: Feature

#272 fix: 앱 출시 후 QA 사안들 반영
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
Labels: For: API, Type: Errors/Bugs

#273 feat: 걷고있는 돈길 포기 시 부모의 acceptedChallenge도 차감 로직 작성 #268
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
Labels: For: API, Status: URGENT, Type: Errors/Bugs

#274 [v1.1.5] 출시 후 이슈 대응 버전 배포
  src/main/java/com/ceos/bankids/constant/ErrorCode.java
  src/main/java/com/ceos/bankids/controller/ChallengeController.java
  src/main/java/com/ceos/bankids/dto/ChallengeDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeDTO.java
  src/main/java/com/ceos/bankids/dto/NoticeListDTO.java
  src/main/java/com/ceos/bankids/dto/NotificationDTO.java
  src/main/java/com/ceos/bankids/dto/OptInDTO.java
  src/main/java/com/ceos/bankids/dto/ProgressDTO.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
  src/main/java/com/ceos/bankids/service/AppleServiceImpl.java
  src/main/java/com/ceos/bankids/service/ChallengeService.java
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
  src/main/java/com/ceos/bankids/service/KidService.java
  src/main/java/com/ceos/bankids/service/KidServiceImpl.java
  src/main/java/com/ceos/bankids/service/ParentService.java
  src/main/java/com/ceos/bankids/service/ParentServiceImpl.java
Labels: For: Deploy

#276 fix: 가족 나가기 API 요청 시, 알림 삭제 #275
  src/main/java/com/ceos/bankids/mapper/FamilyMapper.java
Labels: For: API, Status: URGENT, Type: Errors/Bugs, Type: Refactor

#277 [v1.1.6] 추가 수정버전 배포
  config/nginx/default.conf
  src/main/java/com/ceos/bankids/mapper/FamilyMapper.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy
