Repository bankidz/bankidz-server, pull requests merged in 2022-12, with the labels that each got.

#281 :hammer: refactor: 돈길 알림 로직 분기점 수정
  src/main/java/com/ceos/bankids/service/ChallengeServiceImpl.java
  src/main/java/com/ceos/bankids/service/ExpoNotificationServiceImpl.java
Labels: For: Deploy

#280 feature: 다중기기 접속 방지
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/mapper/AppleMapper.java
  src/main/java/com/ceos/bankids/mapper/KakaoMapper.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
Labels: For: Utils, Type: Feature

#282 fix: 동등 비교 연산자 '==' => Object.equal로 수정
  README.md
  src/main/java/com/ceos/bankids/controller/AppleController.java
  src/main/java/com/ceos/bankids/mapper/AppleMapper.java
  src/main/java/com/ceos/bankids/mapper/ChallengeMapper.java
  src/main/java/com/ceos/bankids/mapper/KakaoMapper.java
  src/main/java/com/ceos/bankids/mapper/UserMapper.java
Labels: Type: Errors/Bugs
